// Code generated by burrow build (Go target) -- VS0-for-Go v0, DO NOT EDIT.

package burrowgen

func SplitSize(total int32, border int32) int32 {
	return ((total - border) / 2)
}

func NextFocusIndex(idx int32, len int32, delta int32) int32 {
	return (((idx + delta) + len) % len)
}
