// Code generated by burrow build (Go target) -- VS0-for-Go v0, DO NOT EDIT.

package burrowgen

type ScalingSpec struct {
	MinReplicas     int32
	MaxReplicas     int32
	CurrentReplicas int32
}

func ClampReplicas(spec ScalingSpec, desired int32) int32 {
	return func() any {
		if desired < (spec).MinReplicas {
			return int32((spec).MinReplicas)
		}
		return int32(func() any {
			if desired > (spec).MaxReplicas {
				return int32((spec).MaxReplicas)
			}
			return int32(desired)
		}().(int32))
	}().(int32)
}
